import fs from 'node:fs'
import path from 'node:path'

export interface SerializableCookie {
  domain?: string
  hostOnly?: boolean
  httpOnly?: boolean
  name: string
  path?: string
  secure?: boolean
  expirationDate?: number
  value: string
}

const BILIBILI_LOGIN_COOKIE_NAMES = new Set(['SESSDATA', 'DedeUserID'])

function isBilibiliCookieDomain(domain: string) {
  const normalized = domain.replace(/^#HttpOnly_/, '').replace(/^\./, '').toLowerCase()
  return normalized === 'bilibili.com' || normalized.endsWith('.bilibili.com')
}

export function hasBilibiliLoginCookie(cookies: SerializableCookie[]) {
  return cookies.some((cookie) => BILIBILI_LOGIN_COOKIE_NAMES.has(cookie.name) && cookie.value)
}

export function serializeBilibiliCookiesToNetscape(cookies: SerializableCookie[]) {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by LifeOS for yt-dlp.',
  ]
  const seen = new Set<string>()
  for (const cookie of cookies) {
    if (!cookie.name || typeof cookie.value !== 'string') continue
    let domain = cookie.domain || '.bilibili.com'
    if (!isBilibiliCookieDomain(domain)) continue
    const pathValue = cookie.path || '/'
    const key = `${domain}\t${pathValue}\t${cookie.name}`
    if (seen.has(key)) continue
    seen.add(key)
    const includeSubdomains = cookie.hostOnly ? 'FALSE' : domain.startsWith('.') ? 'TRUE' : 'FALSE'
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0
    if (cookie.httpOnly && !domain.startsWith('#HttpOnly_')) domain = `#HttpOnly_${domain}`
    lines.push(
      [
        domain,
        includeSubdomains,
        pathValue,
        cookie.secure ? 'TRUE' : 'FALSE',
        String(expires),
        cookie.name,
        cookie.value,
      ].join('\t'),
    )
  }
  return `${lines.join('\n')}\n`
}

export function writeBilibiliCookieFile(filePath: string, cookies: SerializableCookie[]) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, serializeBilibiliCookiesToNetscape(cookies), 'utf8')
}

export function parseBilibiliCookieFile(filePath: string) {
  if (!filePath || !fs.existsSync(filePath)) return undefined
  const pairs: string[] = []
  for (const line of fs.readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    if (!line || (line.startsWith('#') && !line.startsWith('#HttpOnly_'))) continue
    const columns = line.split('\t')
    if (columns.length < 7) continue
    const domain = columns[0].replace(/^#HttpOnly_/, '').toLowerCase()
    if (!domain.includes('bilibili.com')) continue
    pairs.push(`${columns[5]}=${columns[6]}`)
  }
  return pairs.length > 0 ? pairs.join('; ') : undefined
}
