import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const read = (file: string) => readFileSync(path.resolve(file), 'utf8')
const main = read('electron/main.ts')
const preload = read('electron/preload.ts')
const app = read('src/App.tsx')
const rendererEntry = read('src/main.tsx')
const overlay = read('src/components/ScreenCaptureOverlay.tsx')
const editorWindow = read('src/components/ScreenCaptureEditorWindow.tsx')
const toolbox = read('src/views/Toolbox.tsx')
const screenshotTool = read('src/views/ScreenshotTool.tsx')
const pdfOcrOverlay = read('src/components/PdfOcrOverlay.tsx')
const pdfOcrTextLayer = read('src/components/PdfOcrTextLayer.tsx')
const pdfOcrService = read('src/views/pdfOcrService.ts')
const books = read('src/views/Books.tsx')
const settings = read('src/views/Settings.tsx')
const viteConfig = read('vite.config.ts')
const pdfOcrHtml = read('index.html')
const screenCaptureSelection = read('electron/screenCaptureSelection.ts')
const screenshotEditorText = read('src/utils/screenshotEditorText.ts')
const screenshotEditorCrop = read('src/utils/screenshotEditorCrop.ts')
const pencilCursor = read('src/assets/cursors/pencil-cursor.svg')
const mosaicCursor = read('src/assets/cursors/mosaic-cursor.svg')

test('screen capture keeps native capture, clipboard, and file saving behind IPC', () => {
  assert.match(main, /desktopCapturer/)
  assert.match(main, /globalShortcut\.register/)
  assert.match(main, /shortcutRegistration/)
  assert.match(main, /ipcMain\.handle\('screen-capture:capture'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:displays'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:copy'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:save'/)
  assert.match(main, /ipcMain\.handle\(\s*'screen-capture:start'/)
  assert.match(main, /ipcMain\.handle\(\s*'screen-capture:burst'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:recording-source'/)
  assert.match(main, /ipcMain\.handle\(\s*'screen-capture:save-media'/)
  assert.match(main, /setDisplayMediaRequestHandler/)
  assert.match(main, /getMediaAccessStatus\('screen'\)/)
  assert.match(main, /\/usr\/sbin\/screencapture/)
  assert.match(main, /Privacy_ScreenCapture/)
  assert.match(main, /promptForScreenCapturePermission/)
  assert.match(main, /showBurstControlWindow/)
  assert.match(main, /id="elapsed"/)
  assert.match(main, /pausedDuration/)
  assert.match(main, /screen-capture:burst-control/)
  assert.match(main, /openScreenCaptureEditor/)
  assert.match(main, /screen\.getDisplayNearestPoint\(screen\.getCursorScreenPoint\(\)\)/)
  assert.match(main, /selectScreenCaptureArea/)
  assert.match(main, /captureSelectedDisplayArea/)
  assert.match(main, /editorSelectionMode = 'full'/)
  assert.match(main, /if \(screenCaptureInProgress\) return/)
  assert.match(main, /minimizeMainWindowForCapture/)
  assert.match(main, /let restoreMainWindow = true/)
  assert.match(main, /restoreMainWindow = false/)
  assert.match(main, /if \(restoreMainWindow\) showMainWindow\(\)/)
  assert.match(main, /mainWindow\.isMinimized\(\)/)
  assert.match(main, /mainWindow\.restore\(\)/)
  assert.match(main, /appTray\.isDestroyed\(\)/)
  assert.match(preload, /onScreenshotRequested/)
  assert.match(preload, /completeScreenAreaSelection/)
  assert.match(preload, /listScreenDisplays/)
  assert.match(preload, /startScreenCapture/)
  assert.match(preload, /captureScreenBurst/)
  assert.match(preload, /getScreenRecordingSource/)
  assert.match(preload, /saveScreenCaptureMedia/)
  assert.match(preload, /onScreenCaptureBurstProgress/)
  assert.match(preload, /controlScreenCaptureBurst/)
  assert.doesNotMatch(app, /ScreenCaptureOverlay/)
  assert.match(rendererEntry, /#screen-capture-editor/)
  assert.match(rendererEntry, /ScreenCaptureEditorWindow/)
  assert.match(editorWindow, /getScreenCaptureEditorPayload/)
  assert.match(editorWindow, /processing_title/)
  assert.match(main, /screenCaptureEditorWindow/)
  assert.match(main, /title: 'LifeOS 截图'/)
  assert.match(main, /page-title-updated/)
  assert.match(main, /mainWindow\?\.webContents\.getURL\(\)/)
  assert.match(main, /loadScreenCaptureEditorPage/)
  assert.match(main, /attempt < 2/)
  assert.match(main, /isDestroyedElectronError/)
  assert.match(main, /screenCaptureEditorLoadGeneration/)
  assert.match(main, /readError/)
  assert.match(main, /show: false/)
  assert.match(main, /screen-capture:editor-payload/)
  assert.match(main, /screen-capture:open-editor-image/)
  assert.match(main, /await wait\(80\)/)
  assert.match(preload, /getScreenCaptureEditorPayload/)
  assert.match(preload, /onScreenCaptureEditorPayload/)
  assert.match(preload, /openScreenCaptureEditorImage/)
  assert.match(toolbox, /tab_screenshot/)
  assert.match(toolbox, /ScreenshotTool/)
  assert.match(screenshotTool, /startScreenCapture/)
  assert.match(screenshotTool, /captureScreenBurst/)
  assert.match(screenshotTool, /selectionMode: selectArea \? 'rectangle' : undefined/)
  assert.match(screenshotTool, /captureFrames\(true, true\)/)
  assert.match(screenshotTool, /gifDurationSeconds/)
  assert.match(screenshotTool, /getGifCapturePlan/)
  assert.match(
    screenshotTool,
    /captureFrames\(true, true, gifPlan\.frameCount, gifPlan\.interval\)/,
  )
  assert.match(screenshotTool, /whiteSpace: 'normal'/)
  assert.match(screenshotTool, /createGif/)
  assert.match(screenshotTool, /openScreenCaptureEditorImage/)
  assert.match(screenshotTool, /getScreenRecordingSource/)
  assert.match(screenshotTool, /screenshot_mode_long/)
  assert.match(screenshotTool, /pendingMode/)
  assert.match(screenshotTool, /getDisplayMedia/)
  assert.match(overlay, /cropToDataUrl/)
  assert.match(overlay, /copyScreenshot/)
  assert.match(overlay, /saveScreenshot/)
  assert.match(overlay, /selectedDisplayId/)
  assert.match(overlay, /undoEditor/)
  assert.match(overlay, /type EditorTool = 'brush' \| 'mosaic' \| 'text' \| 'crop'/)
  assert.match(overlay, /applyMosaicAt/)
  assert.match(overlay, /imageSmoothingEnabled = false/)
  assert.match(overlay, /commitPendingText/)
  assert.match(overlay, /textLayersRef/)
  assert.match(overlay, /selectedTextId/)
  assert.match(overlay, /drawTextLayer/)
  assert.match(overlay, /editorTool === 'brush'/)
  assert.match(overlay, /\? pencilCursor/)
  assert.match(overlay, /\? mosaicCursor/)
  assert.match(overlay, /\? 'move'/)
  assert.match(overlay, /applyEditorCrop/)
  assert.match(overlay, /resizeScreenshotCrop/)
  assert.match(overlay, /handle: 'north-west'/)
  assert.match(screenshotEditorCrop, /handle === 'move'/)
  assert.match(overlay, /normalizeScreenCaptureSelection/)
  assert.match(overlay, /editorZoom/)
  assert.match(overlay, /ZoomIn/)
  assert.match(overlay, /ZoomOut/)
  assert.match(pencilCursor, /width="32" height="32"/)
  assert.match(mosaicCursor, /pattern id="checker"/)
  assert.match(mosaicCursor, /circle cx="16" cy="16"/)
  assert.match(screenshotEditorText, /screenshotTextContainsPoint/)
  assert.match(screenshotEditorText, /rotation/)
  assert.match(screenshotEditorText, /skewX/)
  assert.match(overlay, /isSavingOutputRef/)
  assert.match(overlay, /event\.button !== 0/)
  assert.match(overlay, /event\.buttons & 1/)
  assert.match(overlay, /onPointerCancel/)
  assert.match(overlay, /onLostPointerCapture/)
  assert.match(overlay, /freeformPoints/)
  assert.match(overlay, /selectionMode === 'freeform'/)
  assert.match(overlay, /let isCurrent = true/)
  assert.match(overlay, /if \(!capture\)/)
  assert.doesNotMatch(overlay, /<X size=\{16\} \/> Esc/)
  assert.match(overlay, /justifyContent: 'center'/)
  assert.match(overlay, /flex: standalone \? '1 1 0'/)
  assert.match(screenCaptureSelection, /new BrowserWindow/)
  assert.match(screenCaptureSelection, /alwaysOnTop: true/)
  assert.match(screenCaptureSelection, /event\.key === 'Escape'/)
  assert.match(screenCaptureSelection, /scaleScreenCaptureSelection/)
  assert.match(screenCaptureSelection, /createFreeformImage/)
  assert.match(screenCaptureSelection, /mode: 'freeform'/)
  assert.match(screenCaptureSelection, /confirmAfterPaint/)
  assert.match(screenCaptureSelection, /processing\.classList\.add\('visible'\)/)
  assert.match(screenCaptureSelection, /requestAnimationFrame/)
  assert.match(screenCaptureSelection, /let confirming = false/)
})

test('reader selection assistance exposes free translation and reusable annotation content', () => {
  assert.match(main, /api\.mymemory\.translated\.net/)
  assert.match(main, /abortController\.abort\(\), 12_000/)
  assert.match(main, /signal: abortController\.signal/)
  assert.match(main, /ipcMain\.handle\(\s*'reader:translate'/)
  assert.match(preload, /translateReaderText/)
  assert.match(books, /handleTranslateSelection/)
  assert.match(books, /translationRequestRef/)
  assert.match(books, /requestId !== translationRequestRef\.current/)
  assert.match(books, /readerTranslationEnabled/)
  assert.match(books, /ai_translation_consent_title/)
  assert.match(books, /save_translation/)
  assert.match(books, /'translation',\s*true/)
  assert.match(books, /readerTranslate: 'Alt\+T'/)
  assert.match(books, /readerAnnotate: 'Alt\+A'/)
  assert.match(books, /readerOcr: 'Alt\+O'/)
  assert.match(books, /requestPdfOcrForCurrentPage/)
  assert.match(books, /handleOpenPdfOcrFallback/)
  assert.match(books, /handlePdfOcrAreasSelected/)
  assert.match(books, /reader-shortcuts:changed/)
  assert.match(books, /e\.isComposing/)
  assert.match(books, /input, textarea, select, button/)
  assert.match(books, /handlePdfOcrRecognized\(text\)/)
  assert.doesNotMatch(books, /cropped\.toDataURL\('image\/png'\)/)
  assert.match(books, /ensurePdfOcrPage\(currentPageIndex \+ 1\)/)
  assert.match(books, /readerSessionRef/)
  assert.match(books, /isCurrentSession/)
  assert.match(books, /cancelPdfOcrRequests/)
  assert.match(books, /signal: abortController\.signal/)
  assert.match(books, /getPdfOcrProgressLabel/)
  assert.match(pdfOcrTextLayer, /ocr_text_layer_label/)
  assert.match(pdfOcrTextLayer, /if \(savedHighlights\.length === 0\) return statusContent/)
  assert.match(pdfOcrTextLayer, /pointerEvents: 'auto'/)
  assert.match(pdfOcrTextLayer, /book-reader__pdf-saved-highlight/)
  assert.match(pdfOcrTextLayer, /progressLabel/)
  assert.match(pdfOcrTextLayer, /onSelectAreas/)
  assert.match(pdfOcrTextLayer, /onSelectAreas\(areas, selectedText\)/)
  assert.match(pdfOcrTextLayer, /const getSelectedText/)
  assert.match(pdfOcrTextLayer, /event\.key !== 'Escape'/)
  assert.match(pdfOcrTextLayer, /handleContextMenu/)
  assert.match(pdfOcrTextLayer, /cancelPointerSelection/)
  assert.match(pdfOcrTextLayer, /onPointerCancel={cancelPointerSelection}/)
  assert.match(pdfOcrTextLayer, /onFallback/)
  assert.match(pdfOcrService, /userRecognitionQueue/)
  assert.match(pdfOcrService, /backgroundRecognitionQueue/)
  assert.match(pdfOcrService, /options\.priority === 'user'/)
  assert.match(pdfOcrService, /AbortSignal/)
  assert.match(pdfOcrService, /workerPromise = null/)
  assert.match(books, /Re-running OCR on a cropped image adds latency/)
  assert.match(pdfOcrOverlay, /createWorker\(\['eng', 'chi_sim'\]/)
  assert.match(pdfOcrOverlay, /workerPath: `\$\{ocrRuntimeBase\}worker\.min\.js`/)
  assert.match(pdfOcrOverlay, /corePath: `\$\{ocrRuntimeBase\}tesseract-core-simd-lstm\.wasm\.js`/)
  assert.match(viteConfig, /Successfully copied OCR worker and WASM runtime files/)
  assert.match(viteConfig, /Warning: Parameter not found:/)
  assert.match(viteConfig, /https:\/\/unpkg\.com\/@tesseract\.js-data/)
  assert.match(pdfOcrHtml, /https:\/\/cdn\.jsdelivr\.net/)
  assert.match(pdfOcrHtml, /https:\/\/unpkg\.com/)
})

test('settings manages the shared shortcut set with duplicate prevention', () => {
  assert.match(settings, /DEFAULT_SHORTCUTS/)
  assert.match(settings, /shortcut_conflict/)
  assert.match(settings, /handleSaveShortcuts/)
  assert.match(settings, /shortcut_system_unavailable/)
  assert.match(settings, /event\.key === 'Escape'/)
  assert.match(settings, /isShortcutModifierKey/)
  assert.match(settings, /handleToggleReaderTranslation/)
  assert.match(settings, /reader_translation_enable/)
  assert.match(settings, /settings\.menu_shortcuts/)
})
