import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const read = (file: string) => readFileSync(path.resolve(file), 'utf8')
const main = read('electron/main.ts')
const preload = read('electron/preload.ts')
const app = read('src/App.tsx')
const overlay = read('src/components/ScreenCaptureOverlay.tsx')
const pdfOcrOverlay = read('src/components/PdfOcrOverlay.tsx')
const pdfOcrTextLayer = read('src/components/PdfOcrTextLayer.tsx')
const pdfOcrService = read('src/views/pdfOcrService.ts')
const books = read('src/views/Books.tsx')
const settings = read('src/views/Settings.tsx')
const viteConfig = read('vite.config.ts')
const pdfOcrHtml = read('index.html')

test('screen capture keeps native capture, clipboard, and file saving behind IPC', () => {
  assert.match(main, /desktopCapturer/)
  assert.match(main, /globalShortcut\.register/)
  assert.match(main, /shortcutRegistration/)
  assert.match(main, /ipcMain\.handle\('screen-capture:capture'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:displays'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:copy'/)
  assert.match(main, /ipcMain\.handle\('screen-capture:save'/)
  assert.match(preload, /onScreenshotRequested/)
  assert.match(preload, /listScreenDisplays/)
  assert.match(app, /ScreenCaptureOverlay/)
  assert.match(overlay, /cropToDataUrl/)
  assert.match(overlay, /copyScreenshot/)
  assert.match(overlay, /saveScreenshot/)
  assert.match(overlay, /selectedDisplayId/)
  assert.match(overlay, /undoEditor/)
  assert.match(overlay, /isSavingOutputRef/)
  assert.match(overlay, /event\.button !== 0/)
  assert.match(overlay, /event\.buttons & 1/)
  assert.match(overlay, /onPointerCancel/)
  assert.match(overlay, /onLostPointerCapture/)
  assert.match(overlay, /let isCurrent = true/)
  assert.match(overlay, /if \(!capture\)/)
})

test('reader selection assistance exposes free translation and reusable annotation content', () => {
  assert.match(main, /api\.mymemory\.translated\.net/)
  assert.match(main, /ipcMain\.handle\(\s*'reader:translate'/)
  assert.match(preload, /translateReaderText/)
  assert.match(books, /handleTranslateSelection/)
  assert.match(books, /translationRequestRef/)
  assert.match(books, /requestId !== translationRequestRef\.current/)
  assert.match(books, /readerTranslationEnabled/)
  assert.match(books, /ai_translation_consent_title/)
  assert.match(books, /ai_use_as_annotation/)
  assert.match(books, /readerTranslate: 'Alt\+T'/)
  assert.match(books, /readerAnnotate: 'Alt\+A'/)
  assert.match(books, /readerOcr: 'Alt\+O'/)
  assert.match(books, /requestPdfOcrForCurrentPage/)
  assert.match(books, /handleOpenPdfOcrFallback/)
  assert.match(books, /handlePdfOcrAreasSelected/)
  assert.match(books, /reader-shortcuts:changed/)
  assert.match(books, /e\.isComposing/)
  assert.match(books, /input, textarea, select, button/)
  assert.match(books, /handlePdfOcrRecognized\(text\)/)
  assert.doesNotMatch(books, /cropped\.toDataURL\('image\/png'\)/)
  assert.match(books, /ensurePdfOcrPage\(currentPageIndex \+ 1\)/)
  assert.match(books, /readerSessionRef/)
  assert.match(books, /isCurrentSession/)
  assert.match(books, /getPdfOcrProgressLabel/)
  assert.match(pdfOcrTextLayer, /ocr_text_layer_label/)
  assert.match(pdfOcrTextLayer, /progressLabel/)
  assert.match(pdfOcrTextLayer, /onSelectAreas/)
  assert.match(pdfOcrTextLayer, /onSelectAreas\(areas, selectedText\)/)
  assert.match(pdfOcrTextLayer, /const getSelectedText/)
  assert.match(pdfOcrTextLayer, /event\.key !== 'Escape'/)
  assert.match(pdfOcrTextLayer, /handleContextMenu/)
  assert.match(pdfOcrTextLayer, /cancelPointerSelection/)
  assert.match(pdfOcrTextLayer, /onPointerCancel={cancelPointerSelection}/)
  assert.match(pdfOcrTextLayer, /onFallback/)
  assert.match(pdfOcrService, /userRecognitionQueue/)
  assert.match(pdfOcrService, /backgroundRecognitionQueue/)
  assert.match(pdfOcrService, /options\.priority === 'user'/)
  assert.match(pdfOcrService, /AbortSignal/)
  assert.match(pdfOcrService, /workerPromise = null/)
  assert.match(books, /Re-running OCR on a cropped image adds latency/)
  assert.match(pdfOcrOverlay, /createWorker\(\['eng', 'chi_sim'\]/)
  assert.match(pdfOcrOverlay, /workerPath: `\$\{ocrRuntimeBase\}worker\.min\.js`/)
  assert.match(pdfOcrOverlay, /corePath: `\$\{ocrRuntimeBase\}tesseract-core-simd-lstm\.wasm\.js`/)
  assert.match(viteConfig, /Successfully copied OCR worker and WASM runtime files/)
  assert.match(viteConfig, /Warning: Parameter not found:/)
  assert.match(viteConfig, /https:\/\/unpkg\.com\/@tesseract\.js-data/)
  assert.match(pdfOcrHtml, /https:\/\/cdn\.jsdelivr\.net/)
  assert.match(pdfOcrHtml, /https:\/\/unpkg\.com/)
})

test('settings manages the shared shortcut set with duplicate prevention', () => {
  assert.match(settings, /DEFAULT_SHORTCUTS/)
  assert.match(settings, /shortcut_conflict/)
  assert.match(settings, /handleSaveShortcuts/)
  assert.match(settings, /shortcut_system_unavailable/)
  assert.match(settings, /event\.key === 'Escape'/)
  assert.match(settings, /isShortcutModifierKey/)
  assert.match(settings, /handleToggleReaderTranslation/)
  assert.match(settings, /reader_translation_enable/)
  assert.match(settings, /settings\.menu_shortcuts/)
})
